### ISSUE TITLE
MailChimpSubscribeForm.prototype.init() is not called

### ISSUE THREAD

**Issue by klokie** [eriklindebratt/mailchimp-subscribe-form#3]
Hej Erik ;)
Are there undeclared dependencies for this library?
I haven't been able to get it to work; seems like [MailChimpSubscribeForm.prototype.init()](https://github.com/eriklindebratt/mailchimp-subscribe-form/blob/master/mailchimp-subscribe-form.js#L57) is never called. Am I missing something?
Thanks

**Comment by eriklindebratt** [comment]
Hi @klokie!
You're right. I actually prefer it that way, not having classes self-instantiate. Noticed that the README was out-of-date though so I just released some updates including an up-to-date README. Thanks for pointing that out! 👍 

In the latest version [`1.2.2`](https://github.com/eriklindebratt/mailchimp-subscribe-form/tree/1.2.2) you can pass an `autoInit` flag in the options object. Hope this solves your problem!

**Comment by klokie** [comment]
Thanks, looks like that should work.
While you're updating the README, it might be good to mention that the HTML should also include at least two other containers, with classes `js-success-message` and `js-error-message`, to hold the potential success and error messages. I found that otherwise the JS will throw an error.
cheers

**Comment by eriklindebratt** [comment]
@klokie Yep I noticed that; the latest release includes includes some additional checks for e.g. those elements, along with some additional options to tap into. Seems so solve it.
